### ISSUE TITLE
Modifiction: Why do we put back Newline Character

### ISSUE THREAD

**Issue by Lldenaurois** [chrisjmccormick/word2vec_commented#1]
I think there's a small mistake in your writeup.

So, we do not require all sentences to be separated by two newline characters. Since we unget(ch) whenever ch == '\n', a single newline character will suffice. That is, when we encounter a single newline character, we put it back. In the next invocation of ReadWord(), we start at a=0 and immediately find our old newline character, so we return the EOS token.

Therefore, it suffices for every sentence to be on a line by itself.

I usually add a space to the end of the line before adding the newline character, but that's just my personal preference.

Let me know if I'm wrong, but this was my understanding of the code.

**Comment by Lldenaurois** [comment]
Also, I would like to contribute. You're doing good work here, and these algorithms form the basis of NLP. Do you accept PRs?

**Comment by chrisjmccormick** [comment]
Yeah, that makes sense, thanks for pointing that out! I was confused by that unget(ch).

And yes, contributions are welcome!

**Comment by chrisjmccormick** [comment]
Finally fixed this, thanks again for pointing it out!
