### ISSUE TITLE
questions with subsampling

### ISSUE THREAD

**Issue by zluo01** [chrisjmccormick/word2vec_commented#6]
Hi , I read over your comment on the subsampling part.
The c implementation is 
`(sqrt(vocab[word].cn / (sample * train_words)) + 1) * (sample * train_words) / vocab[word].cn`

However, in your comment, you says

>  Using the default 'sample' value of 0.001, the equation for ran is:
      ran = (sqrt(x / 0.001) + 1) * (0.001 / x) 

Should it be `ran = (sqrt(x / 0.001 *train_words ) + 1) * (0.001 * train_words / x) ` instead ?

Thank you

**Comment by chrisjmccormick** [comment]
Looks like you figured it out, but the answer is that, in my comment, x = (vocab[word].cn / train_words)

Thanks!
